apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: highload-dns
spec:
  selector:
    app: haproxy
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-stats
  namespace: highload-dns
spec:
  selector:
    app: haproxy
  ports:
    - name: stats
      port: 8404
      targetPort: 8404
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: highload-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
        - name: haproxy
          image: k3d-registry.localhost:5000/haproxy:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
            - containerPort: 8404
