apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: highload-dns
data:
  nginx.conf: |
    events {}
    http {
      upstream backend_up {
        server backend-headless.highload-dns.svc.cluster.local:8000;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://backend_up;
          add_header X-Upstream-Addr $upstream_addr always;
        }

        location /health {
          return 200;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: highload-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: k3d-registry.localhost:5000/nginx:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cfg
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: cfg
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: highload-dns
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
